"""empty message

Revision ID: 2e46d311c7e5
Revises: 733531add80e
Create Date: 2023-11-09 22:38:36.351350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e46d311c7e5'
down_revision = '733531add80e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_points', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_update_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_points', schema=None) as batch_op:
        batch_op.drop_column('last_update_date')

    # ### end Alembic commands ###
