"""empty message

Revision ID: ea9a9c4c7157
Revises: 2e46d311c7e5
Create Date: 2023-11-14 12:32:43.603833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea9a9c4c7157'
down_revision = '2e46d311c7e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank', sa.Integer(), nullable=True))
        batch_op.alter_column('score_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.alter_column('score_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('rank')

    # ### end Alembic commands ###
